packages:
  - apps/*
  - internals/*
  - packages/*
  - scripts
onlyBuiltDependencies:
  - '@biomejs/biome'
  - bufferutil
  - erlpack
  - esbuild
  - sharp
  - zlib-sync
publicHoistPattern:
  - "*bufferutil*"
  - "*erlpack*"
  - "*fzstd*"
  - "*sharp*"
  - "*zlib-sync*"