packages:
  - apps/*
  - packages/*
  - scripts

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - bufferutil
  - erlpack
  - esbuild
  - sharp
  - zlib-sync

publicHoistPattern:
  - '*bufferutil*'
  - '*erlpack*'
  - '*fzstd*'
  - '*sharp*'
  - '*zlib-sync*'
